repos:
  - repo: git://github.com/dnephin/pre-commit-golang
    rev: master
    hooks:
      - id: go-fmt
      - id: go-imports
        args: [-local=github.com/Jguer/yay/v10/]
      - id: golangci-lint
      - id: go-unit-tests
      - id: go-build
